# Generated by Django 3.2.3 on 2021-06-27 10:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=30, unique=True, verbose_name='Pseudonyme'),
        ),
        migrations.CreateModel(
            name='Substitute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateField(auto_now_add=True)),
                ('initial_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='initial_product', to='food.product')),
                ('substituted_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='substituted_product', to='food.product')),
                ('users', models.ManyToManyField(related_name='substitutes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'substitutes',
            },
        ),
    ]
