# Generated by Django 3.2.3 on 2021-06-11 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=250)),
                ('brand', models.CharField(max_length=60)),
                ('barcode', models.CharField(max_length=13)),
                ('nutriscore', models.CharField(max_length=1)),
                ('novascore', models.CharField(max_length=1)),
                ('url', models.URLField()),
                ('image_url', models.URLField(max_length=150)),
            ],
            options={
                'verbose_name_plural': 'products',
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=200, unique=True)),
                ('products', models.ManyToManyField(related_name='stores', to='food.Product')),
            ],
            options={
                'verbose_name_plural': 'stores',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=150, unique=True)),
                ('products', models.ManyToManyField(related_name='categories', to='food.Product')),
            ],
            options={
                'verbose_name_plural': 'categories',
            },
        ),
    ]
