# Generated by Django 3.2.3 on 2021-06-27 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210627_1210'),
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='substitutes',
            field=models.ManyToManyField(through='users.Substitute', to='food.Product'),
        ),
    ]
