# Generated by Django 3.2.3 on 2021-08-30 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-creation_date']},
        ),
        migrations.AlterField(
            model_name='comment',
            name='deletion_date',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
